server:
  port: 8001
  servlet:
    context-path: /

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: 192.168.200.119
      port: 6379
      client-type: jedis

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.atguigu.blog.pojos
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.atguigu.blog.mapper: debug


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    #operations-sorter: order
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'admin-api'
      paths-to-match: '/**'
      packages-to-scan: com.atguigu.blog
  default-flat-param-object: true

knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
